### ISSUE TITLE
Resources monitoring

### ISSUE THREAD

**Issue by victorfranz** [B2W-BIT/restQL-core-java#3]
How can I monitor the usage of memory and cpu by restQL processing?

How async calls are managed (thread pools?) and how to monitor it too?

**Comment by ricardoekm** [comment]
Hi @victorfranz,
On a high-level restQL use Clojure [core.async](http://clojure.com/blog/2013/06/28/clojure-core-async-channels.html) to orchestrate resource invocations (control requests and responses). This is the Clojure implementation of the [CSP](https://en.wikipedia.org/wiki/Communicating_sequential_processes) pattern. All communication is done through what its called channels. restQL implementation doesn't use blocking operation. 

Clojure core.async has a thread pool of 2 * number of cores + 42. The 42 is added to give some margin in case any core.async client implements a blocking operation. If all implementation is non-blocking the 2 * number of cores thread pool size is the optimal value.  Nonetheless, we use the default pool size.

In the low-level (to execute the actual request) we use [Http-Kit](https://github.com/http-kit/http-kit) which in turn uses Java NIO SelectableChannel and SocketChannel. The approach is similar to core.async, however, I'm not sure about the exact underlying thread pool size. 

To sum it up, you don't have to worry about thread issues, the limitation will be the CPU available.

About CPU and memory usage monitoring, when using restQL-core-java, restQL classes will be loaded in the same classpath/JVM of the application. So it's hard to monitor them separately unless you have some APM that allows you to monitor CPU and memory by execution path.

One resource intensive task is the language parsing, so if you're running a resource-intensive workload it's important that you don't concatenate your parameters directly in the query, but rather used the "?" token. That will allow restQL to properly cache your query statements. 

Having said that restQL have before query, after query, before request, after request hooks. That makes APM integration easier (we use that to integrate with New Relic), so you can monitor your query and request times (oops, just realized that this is not currently documented, will open an issue for that).

**Comment by victorfranz-ml** [comment]
Hi @ricardoekm, thanks for the detailed answer!!

Usually I concern about it to know exactly how the application will behave and compete with underlying frameworks for memory and cpu usage.

How to you see an integration of restQL with an implementation of a circuite break or a framework like [histrix](https://github.com/Netflix/Hystrix)?

**Comment by ricardoekm** [comment]
I think Hystrix filled an important gap in the past. However, I believe the future of resilient microservices architecture are non-intrusive solutions provided by service meshs, such as Istio + Kubernetes.

I even think restQL should be integrated into a service mesh. 

Having said that, if anyone in the community develops a Hystrix plugin, we'd be glad to help supporting it.

**Comment by victorfranz-ml** [comment]
Thanks!!!

**Comment by ricardoekm** [comment]
Thank you @victorfranz, please keep feedback coming!
